// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/Common/404.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('./src/components/Common/Loading.vue')['default']
    Menu: typeof import('./src/components/Layout/Menu/index.vue')['default']
    Redirect: typeof import('./src/components/Common/Redirect.vue')['default']
    TagViews: typeof import('./src/components/Layout/TagViews/index.vue')['default']
    WpBreadcrumb: typeof import('wisdom-plus/es')['WpBreadcrumb']
    WpButton: typeof import('wisdom-plus/es')['WpButton']
    WpDropdown: typeof import('wisdom-plus/es')['WpDropdown']
    WpIcon: typeof import('wisdom-plus/es')['WpIcon']
    WpLayout: typeof import('wisdom-plus/es')['WpLayout']
    WpLayoutAside: typeof import('wisdom-plus/es')['WpLayoutAside']
    WpLayoutContent: typeof import('wisdom-plus/es')['WpLayoutContent']
    WpMenu: typeof import('wisdom-plus/es')['WpMenu']
    WpProPageLayout: typeof import('wisdom-plus/es')['WpProPageLayout']
    WpProPermission: typeof import('wisdom-plus/es')['WpProPermission']
    WpSpace: typeof import('wisdom-plus/es')['WpSpace']
    WpSpin: typeof import('wisdom-plus/es')['WpSpin']
    WpTag: typeof import('wisdom-plus/es')['WpTag']
    WpXScroll: typeof import('wisdom-plus/es')['WpXScroll']
  }
}

export { }
