// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        404: typeof import('./src/components/common/404.vue')['default'];
        Actions: typeof import('./src/components/layout/actions/index.vue')['default'];
        AlertContent: typeof import('wp-alert')['AlertContent'];
        AlertFooter: typeof import('wp-alert')['AlertFooter'];
        Arrow: typeof import('./src/components/layout/Header/Arrow.vue')['default'];
        Avatar: typeof import('./src/components/layout/avatar/index.vue')['default'];
        Breadcrumb: typeof import('./src/components/layout/breadcrumb/index.vue')['default'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElTag: typeof import('element-plus/es')['ElTag'];
        Error: typeof import('./src/components/common/error.vue')['default'];
        Footer: typeof import('./src/components/layout/footer/index.vue')['default'];
        Header: typeof import('./src/components/layout/Header/index.vue')['default'];
        HorizontalScrollerMenu: typeof import('./src/components/layout/side-bar/components/horizontal-scroller-menu.vue')['default'];
        Humburger: typeof import('./src/components/layout/humburger/index.vue')['default'];
        Iconfonts: typeof import('./src/components/common/tools/components/iconfonts.vue')['default'];
        IconSelect: typeof import('./src/components/IconSelect.vue')['default'];
        Layout: typeof import('./src/components/layout/index.vue')['default'];
        Loading: typeof import('./src/components/common/loading.vue')['default'];
        Logo: typeof import('./src/components/layout/logo/index.vue')['default'];
        Main: typeof import('./src/components/layout/main.vue')['default'];
        MainLayout: typeof import('./src/components/layout/main-layout.vue')['default'];
        Menu: typeof import('./src/components/layout/Menu/index.vue')['default'];
        NAvatar: typeof import('naive-ui')['NAvatar'];
        Navbar: typeof import('./src/components/layout/navbar/index.vue')['default'];
        NavSideBar: typeof import('./src/components/layout/side-bar/nav-side-bar.vue')['default'];
        NBackTop: typeof import('naive-ui')['NBackTop'];
        NBreadcrumb: typeof import('naive-ui')['NBreadcrumb'];
        NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem'];
        NButton: typeof import('naive-ui')['NButton'];
        NCard: typeof import('naive-ui')['NCard'];
        NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
        NCountdown: typeof import('naive-ui')['NCountdown'];
        NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
        NDropdown: typeof import('naive-ui')['NDropdown'];
        NEl: typeof import('naive-ui')['NEl'];
        NGlobalStyle: typeof import('naive-ui')['NGlobalStyle'];
        NIcon: typeof import('naive-ui')['NIcon'];
        NInput: typeof import('naive-ui')['NInput'];
        NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
        NMenu: typeof import('naive-ui')['NMenu'];
        NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
        NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
        NPopover: typeof import('naive-ui')['NPopover'];
        NResult: typeof import('naive-ui')['NResult'];
        NScrollbar: typeof import('naive-ui')['NScrollbar'];
        NSearchTablePage: typeof import('naive-ui')['NSearchTablePage'];
        NSpin: typeof import('naive-ui')['NSpin'];
        NTag: typeof import('naive-ui')['NTag'];
        Redirect: typeof import('./src/components/common/redirect.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        ScrollerMenu: typeof import('./src/components/layout/side-bar/components/scroller-menu.vue')['default'];
        SelectOption: typeof import('./src/components/SelectOption.vue')['default'];
        SideBar: typeof import('./src/components/layout/side-bar/side-bar.vue')['default'];
        SvgIcon: typeof import('./src/components/layout/svg-icon/index.vue')['default'];
        Tabbar: typeof import('./src/components/layout/tabbar/index.vue')['default'];
        TabSplitSideBar: typeof import('./src/components/layout/side-bar/tab-split-side-bar.vue')['default'];
        TagViews: typeof import('./src/components/layout/TagViews/index.vue')['default'];
        Tools: typeof import('./src/components/common/tools/index.vue')['default'];
        WpAvatar: typeof import('wisdom-plus/es')['WpAvatar'];
        WpButton: typeof import('wisdom-plus/es')['WpButton'];
        WpCountDown: typeof import('wisdom-plus/es')['WpCountDown'];
        WpDropdown: typeof import('wisdom-plus/es')['WpDropdown'];
        WpForm: typeof import('wisdom-plus/es')['WpForm'];
        WpFormItem: typeof import('wisdom-plus/es')['WpFormItem'];
        WpIcon: typeof import('wisdom-plus/es')['WpIcon'];
        WpInput: typeof import('wisdom-plus/es')['WpInput'];
        WpModal: typeof import('wisdom-plus/es')['WpModal'];
        WpProCascader: typeof import('wisdom-plus/es')['WpProCascader'];
        WpProDataPageLayout: typeof import('wisdom-plus/es')['WpProDataPageLayout'];
        WpProForm: typeof import('wisdom-plus/es')['WpProForm'];
        WpProPageLayout: typeof import('wisdom-plus/es')['WpProPageLayout'];
        WpProPersonKeyTransfer: typeof import('wisdom-plus/es')['WpProPersonKeyTransfer'];
        WpProPersonTransfer: typeof import('wisdom-plus/es')['WpProPersonTransfer'];
        WpResult: typeof import('wisdom-plus/es')['WpResult'];
        WpSpace: typeof import('wisdom-plus/es')['WpSpace'];
        WpSpin: typeof import('wisdom-plus/es')['WpSpin'];
        WpTree: typeof import('wisdom-plus/es')['WpTree'];
    }
}
