// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/Common/404.vue')['default']
    DataForm: typeof import('./src/components/DataForm/DataForm.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Menu: typeof import('./src/components/Layout/Menu/index.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    PersonAdd: typeof import('./src/components/Person/PersonAdd.vue')['default']
    PersonTree: typeof import('./src/components/Person/PersonTree.vue')['default']
    Redirect: typeof import('./src/components/Common/Redirect.vue')['default']
    SelectOption: typeof import('./src/components/DataForm/SelectOption.vue')['default']
    TagViews: typeof import('./src/components/Layout/TagViews/index.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}

export { }
