declare const _default: {
    itemPaddingSmall: string;
    itemMarginSmall: string;
    itemMarginSmallRtl: string;
    itemPaddingMedium: string;
    itemMarginMedium: string;
    itemMarginMediumRtl: string;
    itemPaddingLarge: string;
    itemMarginLarge: string;
    itemMarginLargeRtl: string;
    buttonIconSizeSmall: string;
    buttonIconSizeMedium: string;
    buttonIconSizeLarge: string;
    inputWidthSmall: string;
    selectWidthSmall: string;
    inputMarginSmall: string;
    inputMarginSmallRtl: string;
    selectMarginSmall: string;
    prefixMarginSmall: string;
    suffixMarginSmall: string;
    inputWidthMedium: string;
    selectWidthMedium: string;
    inputMarginMedium: string;
    inputMarginMediumRtl: string;
    selectMarginMedium: string;
    prefixMarginMedium: string;
    suffixMarginMedium: string;
    inputWidthLarge: string;
    selectWidthLarge: string;
    inputMarginLarge: string;
    inputMarginLargeRtl: string;
    selectMarginLarge: string;
    prefixMarginLarge: string;
    suffixMarginLarge: string;
};
export default _default;
