declare const _default: {
    itemSize: string;
    itemCellWidth: string;
    itemCellHeight: string;
    scrollItemWidth: string;
    scrollItemHeight: string;
    panelExtraFooterPadding: string;
    panelActionPadding: string;
    calendarTitlePadding: string;
    calendarTitleHeight: string;
    arrowSize: string;
    panelHeaderPadding: string;
    calendarDaysHeight: string;
    calendarTitleGridTempateColumns: string;
    calendarLeftPaddingDate: string;
    calendarLeftPaddingDatetime: string;
    calendarLeftPaddingDaterange: string;
    calendarLeftPaddingDatetimerange: string;
    calendarLeftPaddingMonth: string;
    calendarLeftPaddingYear: string;
    calendarLeftPaddingQuarter: string;
    calendarLeftPaddingMonthrange: string;
    calendarLeftPaddingQuarterrange: string;
    calendarLeftPaddingYearrange: string;
    calendarRightPaddingDate: string;
    calendarRightPaddingDatetime: string;
    calendarRightPaddingDaterange: string;
    calendarRightPaddingDatetimerange: string;
    calendarRightPaddingMonth: string;
    calendarRightPaddingYear: string;
    calendarRightPaddingQuarter: string;
    calendarRightPaddingMonthrange: string;
    calendarRightPaddingQuarterrange: string;
    calendarRightPaddingYearrange: string;
};
export default _default;
