declare const _default: {
    headerFontSize1: string;
    headerFontSize2: string;
    headerFontSize3: string;
    headerFontSize4: string;
    headerFontSize5: string;
    headerFontSize6: string;
    headerMargin1: string;
    headerMargin2: string;
    headerMargin3: string;
    headerMargin4: string;
    headerMargin5: string;
    headerMargin6: string;
    headerPrefixWidth1: string;
    headerPrefixWidth2: string;
    headerPrefixWidth3: string;
    headerPrefixWidth4: string;
    headerPrefixWidth5: string;
    headerPrefixWidth6: string;
    headerBarWidth1: string;
    headerBarWidth2: string;
    headerBarWidth3: string;
    headerBarWidth4: string;
    headerBarWidth5: string;
    headerBarWidth6: string;
    pMargin: string;
    liMargin: string;
    olPadding: string;
    ulPadding: string;
};
export default _default;
