declare const _default: {
    padding: string;
    optionIconSizeSmall: string;
    optionIconSizeMedium: string;
    optionIconSizeLarge: string;
    optionIconSizeHuge: string;
    optionSuffixWidthSmall: string;
    optionSuffixWidthMedium: string;
    optionSuffixWidthLarge: string;
    optionSuffixWidthHuge: string;
    optionIconSuffixWidthSmall: string;
    optionIconSuffixWidthMedium: string;
    optionIconSuffixWidthLarge: string;
    optionIconSuffixWidthHuge: string;
    optionPrefixWidthSmall: string;
    optionPrefixWidthMedium: string;
    optionPrefixWidthLarge: string;
    optionPrefixWidthHuge: string;
    optionIconPrefixWidthSmall: string;
    optionIconPrefixWidthMedium: string;
    optionIconPrefixWidthLarge: string;
    optionIconPrefixWidthHuge: string;
};
export default _default;
