declare const _default: {
    feedbackPadding: string;
    feedbackHeightSmall: string;
    feedbackHeightMedium: string;
    feedbackHeightLarge: string;
    feedbackFontSizeSmall: string;
    feedbackFontSizeMedium: string;
    feedbackFontSizeLarge: string;
    labelFontSizeLeftSmall: string;
    labelFontSizeLeftMedium: string;
    labelFontSizeLeftLarge: string;
    labelFontSizeTopSmall: string;
    labelFontSizeTopMedium: string;
    labelFontSizeTopLarge: string;
    labelHeightSmall: string;
    labelHeightMedium: string;
    labelHeightLarge: string;
    labelPaddingVertical: string;
    labelPaddingHorizontal: string;
    labelTextAlignVertical: string;
    labelTextAlignHorizontal: string;
    labelFontWeight: string;
};
export default _default;
